### ISSUE TITLE
Feature Request: Specify DKIM Key Size

### ISSUE THREAD

**Issue by steilerDev** [huan/docker-simple-mail-forwarder#107]
Hi All,

I have the issue that my DNS provider (hover) does not support 2048 long DKIM keys (they have a size limit on the TXT entry), which is why I need SMF to generate 1024bit long DKIM keys.

I have currently adjusted my local `entrypoint.sh` (in [line 244](https://github.com/huan/docker-simple-mail-forwarder/blob/c3b5b30be708b473ab850fdc36c3734be2d4a614/entrypoint.sh#L244)) to support this. Would it be possible to add an environment variable for this?

Thank you!

**Comment by huan** [comment]
I'd like to accept a PR with a good-named environment variable for configuring this.

**Comment by steilerDev** [comment]
See PR #110

**Comment by huan** [comment]
Thank you very much for your contribution!
