### ISSUE TITLE
Support for ECC keys

### ISSUE THREAD

**Issue by Czocher** [huan/docker-simple-mail-forwarder#50]
Hello,
First of all thanks for all your hard work on the project, it's at least a time saver if not a lifesaver.
My problem is that the only SSL keys I have for my domain are not RSA keys but ECC keys. From what I know postfix support ECC keys by two config options:

```
smtpd_tls_eckey_file = smtpd-key-ecdsa.key
smtpd_tls_eccert_file = smtpd-cert-ecdsa.cert
```

The problem is, from what I see the `main.dist.cf` file accepts only RSA keys with the `smtpd_tls_key_file` and `smtpd_tls_cert_file` directive.

Is there any possibility for ECC key support to be added to the container too?

**Comment by huan** [comment]
Hello, thanks for like the project.

I believe it's do-able to support the ECC keys to the SMF container.

PR will be welcome. :-)

**Comment by Czocher** [comment]
Testing it right now with a substituted configuration, I only changed `smtpd_tls_key_file` to `smtpd_tls_eckey_file` and `smtpd_tls_cert_file` to `smtpd_tls_eccert_file` and it seems to work fine. I'll check a few possibilities (mostly whether you can configure both ECC and RSA keys at the same time without causing postfix a lot of headache.
Gonna get back to you with a proper PR as soon as I test it thoroughly.

**Comment by Czocher** [comment]
Okay the PR is ready: #51 
Tested it on my setup, it doesn't throw any error in the logs although the `smtp.cert/key` is missing, probably cause it sees the `smtp.ec.key` and `smtp.ec.key` as a replacement.
Thanks for the mention in the README, it made my day :dagger:
