### ISSUE TITLE
Multiple forwarding rules

### ISSUE THREAD

**Issue by guysoft** [huan/docker-simple-mail-forwarder#61]
Hey,
Is it possible to have several forwarding rules?

For example:

``one@example.com:one@output.com,two@example.com:one@elsewhere.com``

Note I separated two rules with a comma

**Comment by socke** [comment]
Try semicolon as divider:
`one@example.com:one@output.com,two@example.com:one@elsewhere.com`

See https://github.com/huan/docker-simple-mail-forwarder/blob/master/entrypoint.sh

**Comment by guysoft** [comment]
Great, can see it as an example in the code, also now when searching for a semicolon in the readme I found:
https://github.com/huan/docker-simple-mail-forwarder#3-hardcore

Thanks!

**Comment by BartOrloy** [comment]
it does not work... if i use just one email rule everything works correctly... but if  add second, i see everything same in logs, it generate dkim stuff for both domains... but smtp not listen on 25 port... only difference is i added semicolon separated next domain

btw. i use docker-compose. 

example i changed just domains i dont want share real ones... both are correctly set

this does not work
      - SMF_CONFIG='@xyz.com:xyz@gmail.com;@abc.com:xyz@gmail.com'

this is ok
SMF_CONFIG='@xyz.com:xyz@gmail.com'

**Comment by BartOrloy** [comment]
nope it just does not work... i really hate people like you, who are not able make so simple service like that, and spam google results with your bad work... go to hell...
