### ISSUE TITLE
Configuration file format too old

### ISSUE THREAD

**Issue by fweng322** [huan/docker-simple-mail-forwarder#62]
When I run the docker and see its log, it showed:

https://pastebin.com/fpYsvWz9

It's a warning, but then "stopping the Postfix mail system".  Not sure if it is normal or not.  Self-test is passed, but test mails I sent seems never to be delivered.

**Comment by huan** [comment]
It seems that there's some problem with your environment.

I do not understand what happened, maybe other users could give some information about this?

**Comment by fweng322** [comment]
https://forum.artixlinux.org/index.php/topic,793.0.html

No real affect, just eliminate the warning messages.  SMF worked fine now.

**Comment by huan** [comment]
Glad to hear that!
